version: '3'
services:
  etcd:
    image: bitnami/etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379,http://${INTERFACE_IP}:2379
    ports:
      - "2379:2379"
      - "2380:2380"

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - "0.0.0.0:27017:27017" # for debug
    volumes:
      - ${DATA}/mongo/db:/data/db
      - ${DATA}/mongo/dump:/dump  

  postgres:
    image: postgres:alpine
    restart: always
    container_name: postgres
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/
      - ${DATA}/postgres:/var/lib/postgresql/data
      - ${DATA}/artifacts.bak:/artifacts
    environment:
      - POSTGRES_MULTIPLE_DATABASES=${POSTGRES_DATABASES}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qweasd123      

  gateway:
    image: traefik:latest
    container_name: gateway
    restart: always
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock    

  nextcloud:
    image: nextcloud:26
    restart: always
    container_name: nextcloud
    volumes:
      - ${DATA}/nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=user_nextcloud
      - POSTGRES_PASSWORD=qweasd123
      - NEXTCLOUD_ADMIN_USER=${USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS="nc.rms.local nextcloud"
      - PHP_UPLOAD_LIMIT=40G
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`nc.rms.local`)"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
    depends_on:
      - postgres
      - gateway

  gitea:
    image: gitea/gitea:1.21.3
    restart: always
    container_name: gitea
    volumes:
      - ${DATA}/git:/data
      - ${DATA}/artifacts.bak:/artifacts
    environment:
      - ROOT_URL="http://git.rms.local/"
      - APP_NAME="Gitea:My private Git repository"
      - USER_UID=1000
      - USER_GID=1000
      - DISABLE_REGISTRATION=true
      - REQUIRE_SIGNIN_VIEW=true
      - DB_TYPE=postgres
      - DB_HOST=postgres:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=qweasd123
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
      - "traefik.http.routers.gitea.rule=Host(`git.rms.local`)"
    depends_on:
      - postgres
      - gateway

  web:
    image: racoonmediaserver/web:latest
    restart: always
    container_name: web
    volumes:
      - ./rms-web/rms-web.json:/etc/rms/rms-web.json 
      - ${MEDIA}/library:/media
      - ${MEDIA}/backup:/backup
    environment:
      - RMS_CCTV_ENABLED=true
      - RMS_CONTENT_BACKUPS=/backup
      - TZ=Europe/Moscow
      - MICRO_REGISTRY=etcd
      - MICRO_REGISTRY_ADDRESS=etcd:2379
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`rms.local`)"
      - "traefik.http.services.web.loadbalancer.server.port=8080"
      - "com.centurylinklabs.watchtower.enable=true"     
    depends_on:
      - gateway
      - etcd

  bot-client:
    image: racoonmediaserver/bot-client:latest
    restart: always
    container_name: bot-client
    environment:
      - TZ=Europe/Moscow
      - RMS_DEVICE=${DEVICE}
      - RMS_REMOTE_HOST=${REMOTE_HOST}
      - RMS_REMOTE_PORT=${REMOTE_PORT}
      - MICRO_REGISTRY=etcd
      - MICRO_REGISTRY_ADDRESS=etcd:2379
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - etcd

  torrent:
    image: racoonmediaserver/torrent:latest
    restart: always
    container_name: torrent
    environment:
      - RMS_DATABASE=/media/library/torrents/db
      - MICRO_REGISTRY=etcd
      - MICRO_REGISTRY_ADDRESS=etcd:2379
    volumes:
      - ${MEDIA}/library/torrents:/media/library/torrents
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - etcd

  library:
    image: racoonmediaserver/library:latest
    restart: always
    container_name: library
    environment:
      - RMS_DEVICE=${DEVICE}
      - RMS_DATABASE=mongodb://mongo:27017/library
      - RMS_REMOTE_HOST=${REMOTE_HOST}
      - RMS_REMOTE_PORT=${REMOTE_PORT}
      - MICRO_BROKER_ADDRESS=0.0.0.0:5531
      - MICRO_REGISTRY=etcd
      - MICRO_REGISTRY_ADDRESS=etcd:2379
    volumes:
      - ${MEDIA}/library:/media/library
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - mongo
      - etcd

  notifier:
    image: racoonmediaserver/notifier:latest
    restart: always
    container_name: notifier
    environment:
      - RMS_DEVICE=${DEVICE}
      - RMS_DATABASE=mongodb://mongo:27017/notifier
      - RMS_REMOTE_HOST=${REMOTE_HOST}
      - RMS_REMOTE_PORT=${REMOTE_PORT}
      - MICRO_BROKER_ADDRESS=0.0.0.0:5531
      - MICRO_REGISTRY=etcd
      - MICRO_REGISTRY_ADDRESS=etcd:2379
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - mongo
      - etcd

  notes:
    image: racoonmediaserver/notes:latest
    restart: always
    container_name: notes
    environment:
      - TZ=Europe/Moscow
      - RMS_DATABASE_HOST=postgres
      - MICRO_REGISTRY=etcd
      - MICRO_REGISTRY_ADDRESS=etcd:2379
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - bot-client
      - nextcloud
      - etcd

  backup:
    image: racoonmediaserver/backup:latest
    restart: always
    container_name: backup
    environment:
      - TZ=Europe/Moscow
      - RMS_DATABASE_HOST=postgres
      - RMS_SERVICES_NEXTCLOUD_DATA=/data/nc
      - RMS_DEBUG_VERBOSE=true
      - MICRO_REGISTRY=etcd
      - MICRO_REGISTRY_ADDRESS=etcd:2379
    volumes:
      - ${MEDIA}/backup:/backups
      - ${DATA}/artifacts.bak:/artifacts
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA}/nextcloud:/data/nc:ro
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - postgres
      - etcd

  cctv:
    image: racoonmediaserver/cctv:latest
    restart: always
    container_name: cctv
    environment:
      - TZ=Europe/Moscow
      - RMS_DATABASE_HOST=postgres
      - RMS_DEBUG_VERBOSE=true
      - MICRO_REGISTRY=etcd
      - MICRO_REGISTRY_ADDRESS=etcd:2379
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - postgres
      - etcd 

  dlna:
    container_name: dlna
    build: ./serviio
    restart: always
    environment:
      - RMS_IP_ADDR=${INTERFACE_IP}
    volumes:
      - ./serviio/config:/opt/serviio/config
      - ${MEDIA}/library:/media/library
    network_mode: "host"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --label-enable
